version: 2
jobs:
  build:
    working_directory: /go/src/github.com/saromanov/clickhouse-metrics
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run: go vet ./...
    - run: go test ./...
  test:
    pre:
      - go get github.com/mattn/goveralls
    override:
      - go test -v -cover -race -coverprofile=/home/ubuntu/coverage.out
    post:
      - /home/ubuntu/.go_workspace/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci -repotoken=12aOcrQk9PXfM3KQgvQXCYn515GG3bi8x