version: 2
jobs:
  build:
    working_directory: /go/src/github.com/saromanov/clickhouse-metrics
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run: go get github.com/mattn/goveralls
    - run: go get github.com/stretchr/testify/assert
    - run: go get ./...
    - run: go vet ./...
    - run: go test